from .overlay import ScreenOverlay, DEFAULT_DISPLAY_INDEX, DEFAULT_DISPLAY_MESSAGE, DEFAULT_FONT_SIZE
from .tray_icon import SystemTrayIcon, DEFAULT_NAME


class DEFAULT:
    NAME = DEFAULT_NAME
    DISPLAY = DEFAULT_DISPLAY_INDEX
    MESSAGE = DEFAULT_DISPLAY_MESSAGE
    FONT_SIZE = DEFAULT_FONT_SIZE
